version: '3.1'

services:
  jrtb-bot:
    depends_on:
      - db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: "jrtb"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080