# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: "jrtb"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080